apiVersion: v1
kind: Service
metadata:
  name: achat-app-service
  namespace: achat-app
  labels:
    app: achat-app
spec:
  type: NodePort
  selector:
    app: achat-app
  ports:
  - port: 8080
    targetPort: 8089
    nodePort: 30080
    protocol: TCP
    name: http
  sessionAffinity: None

