apiVersion: v1
kind: Service
metadata:
  name: achat-app-service
  namespace: achat-app
  labels:
    app: achat-app
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
spec:
  type: LoadBalancer
  selector:
    app: achat-app
  ports:
  - port: 80
    targetPort: 8089
    protocol: TCP
    name: http
  sessionAffinity: None

